In [1]:
import pandas as pd
import os
import shutil
os.getcwd()

'/mnt/hum01-home01/p88346bn/test/project/ctgan-bbb/code'

In [19]:
data1 = pd.read_csv('evals_best_pbb.csv',header=None)
data1.columns = ['dataset','loss','method','kld_weight','mc_sample_train','bayes','sim','mc_sample',
                 'roc_uni','roc_bi','cio','utility','risk']
# data1.loc[(data1['method']=='CTGAN') & (data1['kld_weight'] != '1'),'method'] = 'bbb'
data1['risk'] = data1['risk'].clip(0, None)
data1['score'] = (data1['utility'] + (1-data1['risk']))/2
data1.head()

,dataset,loss,method,kld_weight,mc_sample_train,bayes,sim,mc_sample,roc_uni,roc_bi,cio,utility,risk,score
0,UK,wasserstein,CTGAN,1,1,False,0,1,0.697993,0.550969,0.153020,0.467327,0.329722,0.568802
1,UK,wasserstein,CTGAN,1,1,False,0,2,0.687062,0.538334,0.187491,0.470962,0.339352,0.565805
2,UK,wasserstein,CTGAN,1,1,False,0,5,0.677014,0.523570,0.139517,0.446700,0.357489,0.544605
3,UK,wasserstein,CTGAN,1,1,False,0,10,0.674035,0.516755,0.136479,0.442423,0.365465,0.538479
4,UK,wasserstein,CTGAN,1,1,False,1,1,0.694570,0.547560,0.191436,0.477856,0.326527,0.575664

In [20]:
data_max = data1.groupby(['dataset','loss','method','kld_weight','mc_sample_train','bayes','mc_sample'])['score'].max().reset_index()
data_max = data_max.merge(data1[['sim','roc_uni','roc_bi','cio','utility','risk','score']],on='score')
data_max.head()

,dataset,loss,method,kld_weight,mc_sample_train,bayes,mc_sample,score,sim,roc_uni,roc_bi,cio,utility,risk
0,Adult,vanilla,CTGAN,1,1,False,1,0.657798,3,0.726061,0.551408,0.232762,0.503410,0.187814
1,Adult,vanilla,CTGAN,1,1,False,2,0.605222,3,0.726454,0.553753,0.273001,0.517736,0.307293
2,Adult,vanilla,CTGAN,1,1,False,5,0.578240,0,0.701904,0.533301,0.280875,0.505360,0.348880
3,Adult,vanilla,CTGAN,1,1,False,10,0.547083,1,0.688078,0.519724,0.191906,0.466570,0.372404
4,Adult,vanilla,bbb,1m,2,True,1,0.742069,0,0.768046,0.532842,0.151524,0.484137,0.000000

In [21]:
bbb_f = []
for i in range(len(data_max)):
    if data_max['method'][i] == 'CTGAN':
        bbb_f.append(data_max['loss'][i])
    elif data_max['method'][i] == 'bbb':
        bbb_f.append('bbb'+'-'+data_max['loss'][i][0])
    else:
        bbb_f.append(data_max['method'][i])
data_max['bbb_function'] = bbb_f

In [51]:
data_max.columns, data2.columns

(Index(['dataset', 'loss', 'method', 'kld_weight', 'mc_sample_train', 'bayes',
        'mc_sample', 'score', 'sim', 'roc_uni', 'roc_bi', 'cio', 'utility',
        'risk', 'bbb_function'],
       dtype='object'),
 Index(['dataset', 'discbayes', 'bbb_function', 'final_val', 'Utility.x',
        'Risk.x', 'mc_sample_train', 'mc_sample', 'kl_weight', 'Utility.y',
        'Risk.y', 'id'],
       dtype='object'))

In [22]:
data2 = pd.read_csv('best_bbb_pbb_seed_1.csv')
final_data_sim = data_max.merge(data2[['dataset','bbb_function','mc_sample']], on=['dataset','bbb_function','mc_sample'])

In [44]:
final_data_sim

,dataset,loss,method,kld_weight,mc_sample_train,bayes,mc_sample,score,sim,roc_uni,roc_bi,cio,utility,risk,bbb_function
0,Adult,vanilla,CTGAN,1,1,False,1,0.657798,3,0.726061,0.551408,0.232762,0.503410,0.187814,vanilla
1,Adult,vanilla,bbb,1m,2,True,1,0.742069,0,0.768046,0.532842,0.151524,0.484137,0.000000,bbb-v
2,Adult,vanilla,fclassic,1m,5,True,1,0.741083,0,0.759986,0.526269,0.178352,0.488202,0.006037,fclassic
3,Adult,vanilla,flamb,2mi,2,True,2,0.741021,0,0.761053,0.523172,0.161900,0.482041,0.000000,flamb
4,Adult,vanilla,fquad,2mi,5,True,1,0.736887,2,0.753417,0.522339,0.145569,0.473775,0.000000,fquad
5,Adult,wasserstein,CTGAN,1,1,False,1,0.613082,4,0.726867,0.560372,0.263199,0.516813,0.290648,wasserstein
6,Adult,wasserstein,bbb,2mi,1,True,1,0.756200,0,0.798434,0.586284,0.166772,0.517163,0.004763,bbb-w
7,Canada,vanilla,CTGAN,1,1,False,1,0.664376,2,0.751137,0.582401,0.259900,0.531146,0.202393,vanilla
8,Canada,vanilla,bbb,2mi,1,True,1,0.725016,4,0.794189,0.604588,0.081845,0.493541,0.043508,bbb-v
9,Canada,vanilla,fclassic,2mi,5,True,1,0.716883,0,0.833120,0.632095,0.093936,0.519717,0.085951,fclassic
10,Canada,vanilla,flamb,1m,1,True,1,0.724192,0,0.767322,0.573744,0.100361,0.480475,0.032091,flamb
11,Canada,vanilla,fquad,2mi,5,True,1,0.745062,4,0.817391,0.610245,0.045673,0.491103,0.000979,fquad
12,Canada,wasserstein,CTGAN,1,1,False,1,0.670226,1,0.800285,0.631302,0.151181,0.527589,0.187137,wasserstein
13,Canada,wasserstein,bbb,2mi,1,True,1,0.677738,0,0.810032,0.626788,0.080953,0.505924,0.150448,bbb-w
14,Churn,vanilla,CTGAN,1,1,False,1,0.835930,2,0.805419,0.710164,0.500000,0.671861,0.000000,vanilla
15,Churn,vanilla,bbb,1m,1,True,2,0.849668,1,0.846675,0.751330,0.500000,0.699335,0.000000,bbb-v
16,Churn,vanilla,fclassic,2mi,5,True,2,0.847926,3,0.835474,0.752081,0.500000,0.695852,0.000000,fclassic
17,Churn,vanilla,flamb,2mi,1,True,1,0.844645,2,0.828909,0.738964,0.500000,0.689291,0.000000,flamb
18,Churn,vanilla,fquad,1m,1,True,1,0.843896,3,0.830702,0.732676,0.500000,0.687793,0.000000,fquad
19,Churn,wasserstein,CTGAN,1,1,False,1,0.819187,4,0.743782,0.671339,0.500000,0.638374,0.000000,wasserstein
20,Churn,wasserstein,bbb,1m,5,True,1,0.850982,2,0.848052,0.757840,0.500000,0.701964,0.000000,bbb-w
21,Fiji,vanilla,CTGAN,1,1,False,1,0.531874,4,0.700351,0.560168,0.056441,0.438987,0.375239,vanilla
22,Fiji,vanilla,bbb,2mi,1,True,1,0.572104,1,0.771632,0.582487,0.206107,0.520075,0.375867,bbb-v
23,Fiji,vanilla,fclassic,1m,1,True,1,0.554080,2,0.721841,0.544326,0.160714,0.475627,0.367467,fclassic
24,Fiji,vanilla,flamb,1m,1,True,1,0.588752,3,0.703484,0.527564,0.150324,0.460457,0.282952,flamb
25,Fiji,vanilla,fquad,1m,2,True,1,0.595664,2,0.697817,0.518239,0.103770,0.439942,0.248614,fquad
26,Fiji,wasserstein,CTGAN,1,1,False,1,0.546757,1,0.696233,0.553915,0.261600,0.503916,0.410402,wasserstein
27,Fiji,wasserstein,bbb,2mi,1,True,1,0.552776,1,0.724386,0.532720,0.075657,0.444254,0.338701,bbb-w
28,Indonesia,vanilla,CTGAN,1,1,False,1,0.587413,3,0.743164,0.551941,0.024126,0.439744,0.264917,vanilla
29,Indonesia,vanilla,bbb,2mi,5,True,1,0.603376,0,0.700248,0.586831,0.105324,0.464134,0.257382,bbb-v
30,Indonesia,vanilla,fclassic,2mi,5,True,1,0.612665,4,0.728747,0.583743,0.067248,0.459913,0.234582,fclassic
31,Indonesia,vanilla,flamb,2mi,2,True,1,0.578542,3,0.697569,0.497541,0.071978,0.422362,0.265278,flamb
32,Indonesia,vanilla,fquad,1m,2,True,1,0.686315,0,0.744030,0.532276,0.039600,0.438635,0.066006,fquad
33,Indonesia,wasserstein,CTGAN,1,1,False,1,0.602445,0,0.734931,0.543964,0.081359,0.453418,0.248528,wasserstein
34,Indonesia,wasserstein,bbb,1m,5,True,1,0.565638,4,0.770076,0.586320,0.104005,0.486800,0.355525,bbb-w
35,Rwanda,vanilla,CTGAN,1,1,False,1,0.539090,4,0.636712,0.580308,0.064417,0.427146,0.348965,vanilla
36,Rwanda,vanilla,bbb,2mi,1,True,1,0.658191,3,0.716508,0.619590,0.198818,0.511639,0.195257,bbb-v
37,Rwanda,vanilla,fclassic,1m,1,True,2,0.659296,3,0.741090,0.653293,0.357045,0.583809,0.265217,fclassic
38,Rwanda,vanilla,flamb,2mi,5,True,2,0.668864,4,0.730521,0.647157,0.319349,0.565676,0.227947,flamb
39,Rwanda,vanilla,fquad,1m,5,True,2,0.658573,1,0.716518,0.641537,0.249916,0.535990,0.218844,fquad
40,Rwanda,wasserstein,CTGAN,1,1,False,1,0.511844,1,0.631397,0.581886,0.150025,0.454436,0.430749,wasserstein
41,Rwanda,wasserstein,bbb,2mi,5,True,1,0.592409,4,0.643969,0.563614,0.052992,0.420192,0.235374,bbb-w
42,UK,vanilla,CTGAN,1,1,False,1,0.569949,1,0.717014,0.587486,0.129515,0.478005,0.338106,vanilla
43,UK,vanilla,bbb,2mi,1,True,1,0.600932,3,0.781695,0.633914,0.107462,0.507690,0.305827,bbb-v
44,UK,vanilla,fclassic,1m,1,True,1,0.622290,0,0.802051,0.638857,0.241034,0.560647,0.316068,fclassic
45,UK,vanilla,flamb,2mi,1,True,1,0.621499,4,0.787847,0.640017,0.072450,0.500105,0.257106,flamb
46,UK,vanilla,fquad,2mi,1,True,1,0.642358,3,0.824904,0.661168,0.187362,0.557812,0.273096,fquad
47,UK,wasserstein,CTGAN,1,1,False,1,0.575664,1,0.694570,0.547560,0.191436,0.477856,0.326527,wasserstein
48,UK,wasserstein,bbb,1m,1,True,1,0.576730,0,0.747636,0.629877,0.116353,0.497955,0.344495,bbb-w

In [40]:
final_data_sim.to_csv('final_best_bbb.csv',index=False)

In [24]:
import shutil
for i in range(len(final_data_sim)):
    filename1 = f"best_{final_data_sim['dataset'][i]}_{final_data_sim['method'][i]}_{final_data_sim['loss'][i]}_{final_data_sim['mc_sample'][i]}_{final_data_sim['sim'][i]}.csv"
    src = f'{os.getcwd()}/data_sim_20240528/{filename1}'
    dst = f'{os.getcwd()}/best_for_vis/{filename1}'
#     filename1, src, dst
    shutil.copyfile(src, dst)

In [38]:
data_mcmc = pd.read_csv(os.getcwd()+'/mcmc_synth_data_res.csv')
data_mcmc.columns = ['dataset','method','sample','sim',
                 'roc_uni','roc_bi','cio','utility','risk']
data_mcmc['risk'] = data_mcmc['risk'].clip(0, None)
data_mcmc['score'] = (data_mcmc['utility'] + (1-data_mcmc['risk']))/2

In [46]:
data_max_mcmc = data_mcmc.groupby(['dataset','method','sample'])['score'].max().reset_index()
data_max_mcmc = data_max_mcmc.merge(data_mcmc[['sim','roc_uni','roc_bi','cio','utility','risk','score']],on='score')
data_max_mcmc

,dataset,method,sample,score,sim,roc_uni,roc_bi,cio,utility,risk
0,Adult,ASGHMC,bma,0.661960,3,0.549462,0.353223,0.069075,0.323920,0.000000
1,Adult,ASGHMC,concat,0.661376,4,0.541751,0.347280,0.079227,0.322753,0.000000
2,Adult,ASGHMC,wa,0.662556,0,0.540174,0.349200,0.085961,0.325112,0.000000
3,Adult,PSGLD,bma,0.721432,4,0.757813,0.516847,0.104087,0.459582,0.016719
4,Adult,PSGLD,concat,0.727350,2,0.745107,0.511188,0.107807,0.454701,0.000000
5,Adult,PSGLD,wa,0.728370,3,0.747878,0.514933,0.107409,0.456740,0.000000
6,Canada,ASGHMC,bma,0.564265,1,0.520736,0.360007,0.105809,0.328851,0.200320
7,Canada,ASGHMC,concat,0.728258,0,0.775991,0.577912,0.015647,0.456517,0.000000
8,Canada,ASGHMC,wa,0.731121,0,0.776021,0.577667,0.033036,0.462241,0.000000
9,Canada,PSGLD,bma,0.719123,0,0.760498,0.553826,0.000413,0.438246,0.000000
10,Canada,PSGLD,concat,0.723238,0,0.745942,0.542833,0.050655,0.446476,0.000000
11,Canada,PSGLD,wa,0.723510,3,0.746683,0.543211,0.051166,0.447020,0.000000
12,Churn,ASGHMC,bma,0.610045,4,0.320704,0.209921,0.500000,0.343542,0.123451
13,Churn,ASGHMC,concat,0.658452,1,0.499303,0.393063,0.500000,0.464122,0.147218
14,Churn,ASGHMC,wa,0.661785,4,0.504298,0.396044,0.500000,0.466781,0.143211
15,Churn,PSGLD,bma,0.860893,2,0.878089,0.787271,0.500000,0.721787,0.000000
16,Churn,PSGLD,concat,0.853675,2,0.854818,0.767234,0.500000,0.707351,0.000000
17,Churn,PSGLD,wa,0.853744,2,0.855743,0.766721,0.500000,0.707488,0.000000
18,Fiji,ASGHMC,bma,0.509364,0,0.592209,0.458787,0.053571,0.368189,0.349462
19,Fiji,ASGHMC,concat,0.593632,2,0.689594,0.498024,0.063247,0.416955,0.229691
20,Fiji,ASGHMC,wa,0.578422,0,0.690478,0.496668,0.114184,0.433777,0.276933
21,Fiji,PSGLD,bma,0.595824,0,0.677602,0.452474,0.090277,0.406784,0.215136
22,Fiji,PSGLD,concat,0.606077,0,0.677138,0.454860,0.150351,0.427450,0.215296
23,Fiji,PSGLD,wa,0.603492,4,0.674449,0.453700,0.092953,0.407034,0.200049
24,Indonesia,ASGHMC,bma,0.567588,0,0.687402,0.444872,0.279356,0.470543,0.335367
25,Indonesia,ASGHMC,concat,0.554749,3,0.678548,0.442591,0.278883,0.466674,0.357177
26,Indonesia,ASGHMC,wa,0.580341,4,0.675769,0.444858,0.278883,0.466503,0.305821
27,Indonesia,PSGLD,bma,0.607472,0,0.641283,0.415247,0.283611,0.446714,0.231769
28,Indonesia,PSGLD,concat,0.648496,4,0.637263,0.412762,0.266859,0.438962,0.141970
29,Indonesia,PSGLD,wa,0.608020,0,0.642183,0.416058,0.277368,0.445203,0.229163
30,Rwanda,ASGHMC,bma,0.498633,4,0.306240,0.427133,0.233671,0.322348,0.325082
31,Rwanda,ASGHMC,concat,0.644636,2,0.510391,0.376979,0.126622,0.337997,0.048726
32,Rwanda,ASGHMC,wa,0.656476,4,0.514257,0.382337,0.153426,0.350007,0.037054
33,Rwanda,PSGLD,bma,0.596987,4,0.574758,0.471711,0.125115,0.390528,0.196555
34,Rwanda,PSGLD,concat,0.645245,3,0.563410,0.448049,0.093604,0.368354,0.077865
35,Rwanda,PSGLD,wa,0.601783,0,0.567297,0.455857,0.124180,0.382445,0.178879
36,UK,ASGHMC,bma,0.603201,1,0.744982,0.559651,0.060955,0.455196,0.248793
37,UK,ASGHMC,concat,0.667598,0,0.823375,0.613829,0.001832,0.479679,0.144482
38,UK,ASGHMC,wa,0.669741,0,0.821452,0.613751,0.000000,0.478401,0.138918
39,UK,PSGLD,bma,0.655598,0,0.741993,0.525724,0.038663,0.435460,0.124265
40,UK,PSGLD,concat,0.653355,0,0.742858,0.528320,0.027237,0.432805,0.126095
41,UK,PSGLD,wa,0.656094,2,0.741152,0.529735,0.011294,0.427394,0.115205

In [47]:
data_max_mcmc.to_csv('final_best_mcmc.csv',index=False)

In [50]:
import shutil
for i in range(len(data_max_mcmc)):
    filename1 = f"best_{data_max_mcmc['dataset'][i]}_{data_max_mcmc['method'][i]}_vanilla_{data_max_mcmc['sample'][i]}_{data_max_mcmc['sim'][i]}.csv"
    src = f'{os.getcwd()}/data_sim_20240528/{filename1}'
    dst = f'{os.getcwd()}/best_for_vis/{filename1}'
#     print(filename1, src, dst)
    shutil.copyfile(src, dst)